const Products = [
  {
    Id: "1",
    Image: "Black_Tshirt.png",
    Name: "T-SHIRT WITH TAPE DETAILS",
    
    Price: "200",
    offerPrice: "120",
    desc: "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
    sizeSmall: "exist",
    sizeMedium: "notExist",
    sizeLarge: "exist",
    sizeXLarge: "exist",
    reviews: [{ name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",Rating: "4.5",},
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",Rating: "4.5",},
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",Rating: "4.5",},
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",Rating: "4.5",},,
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",Rating: "4.5",},
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",Rating: "4.5",},
   
  ],
  },
  {
    Id: "2",
    Image: "jeans1.png",
    Name: "SKINNY FIT JEANS",
    Price: "260",
    offerPrice: "240",
    desc: "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
    sizeSmall: "notExist",
    sizeMedium: "exist",
    sizeLarge: "exist",
    sizeXLarge: "exist",
    reviews: [{ name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",    Rating: "3.5",  },
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",    Rating: "3.5"},
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",    Rating: "3.5"},,
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",    Rating: "3.5"},,
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",    Rating: "3.5"},
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",    Rating: "3.5"},
    
  ],
  },
  {
    Id: "3",
    Image: "Red_Shirt.png",
    Name: "CHECKERED SHIRT",
    Price: "220",
    offerPrice: "180",
    desc: "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
    sizeSmall: "exist",
    sizeMedium: "notExist",
    sizeLarge: "notExist",
    sizeXLarge: "exist",
    reviews: [{ name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",  Rating: "4.5",},
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",  Rating: "4.5",},
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",  Rating: "4.5",},,
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",  Rating: "4.5",},,
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",  Rating: "4.5",},
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",  Rating: "4.5",},
    
  ],
  },
  {
    Id: "4",
    Image: "Orange_tshirt.png",
    Name: "SLEEVE STRIPED T-SHIRT",
    Price: "160",
    offerPrice: "130",
    desc: "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
    sizeSmall: "notExist",
    sizeMedium: "notExist",
    sizeLarge: "exist",
    sizeXLarge: "exist",
    reviews: [{ name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",  Rating: "4.5",},
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",  Rating: "4.5",},
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",  Rating: "4.5",},,
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",  Rating: "4.5",},,
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",  Rating: "4.5",},
    { name: "Samantha D." ,
    review:"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. Its become my favorite go-to shirt.",
    posted:"Posted on August 14, 2023",  Rating: "4.5",},
  ],
  },

  // {
  //   Id: "Pro-5",
  //   Image: "green_shirt.png",
  //   Name: "Vertical Striped Shirt",
  //   Rating: "5",
  //   Price: "232",
  //   offerPrice: "212",
  //   off:"-20%"
  // },
  // {
  //   Id: "Pro-6",
  //   Image: "Orange_down_tshirt.png",
  //   Name: "COURAGE GRAPHIC T-SHIRT",
  //   Rating: "4",
  //   Price: "145",
  // },
  // {
  //   Id: "Pro-7",
  //   Image: "Shorts.png",
  //   Name: "LOOSE FIT BERMUDA SHORTS",
  //   Rating: "3",
  //   Price: "80",
  // },
  // {
  //   Id: "Pro-8",
  //   Image: "Blackpent.png",
  //   Name: "FADED SKINNY JEANS",
  //   Rating: "4.5",
  //   Price: "210",

  // },
];
module.exports = { Products };
